# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

In [2]:
## Looping Through Arrays

In [3]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [4]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [5]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop iterates over each row of arrA and prints the whole row multiplied by 2.
The second loop goes into each individual element in each row and prints each number multiplied by 2.

In [7]:
for x in arrA:
    for y in x:
        loop_result = x * 2  # x*2 multiplies the whole row, not just y
print(loop_result)
# loop_result only shows the last row x2 because the loop keeps overwriting it

[28 30 32]


## Joining and Stacking Arrays

joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

In [15]:
# This will cause an error - that is expected!
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
# Error: joined_array_1 is shape (4,3) and joined_array_2 is shape (2,6)
# np.stack requires both arrays to have the exact same shape

NameError: name 'joined_array_1' is not defined

another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

In [16]:
# This will cause an error - that is expected!
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
# Error: joined_array_1 has 4 rows but arrA only has 2 rows
# To join side by side on axis=1, both arrays must have the same number of rows

NameError: name 'joined_array_1' is not defined

In [17]:
h = np.hstack((arrA, arrA))
print(h)
# hstack joins arrays side by side (left to right)

v = np.vstack((arrA, arrA))
print(v)
# vstack joins arrays on top of each other (up and down)

d = np.dstack((arrA, arrA))
print(d)
# dstack joins arrays along a third depth dimension

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [18]:
splitsky = np.split(joined_array_1, 2)
print(splitsky)
# Result: 2 arrays, each is 2D with 2 rows and 3 columns

NameError: name 'joined_array_1' is not defined

In [19]:
spliterino = np.split(joined_array_1, 3)
print(spliterino)
# Result: 3 arrays, each is still 2D with 1 row and 3 columns

NameError: name 'joined_array_1' is not defined

## Searching and Replacing Array Values

In [20]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)
# arrA % 2 == 0 checks if each number is even
# If even: print the number from arrA. If odd: print the word 'odd'

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [22]:
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [23]:
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [24]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[ 7 13  7]
