# Exercise 1.B NumPy Random

In [3]:
import numpy as np

## Generating Random Numbers

In [4]:
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

[18  5]


In [6]:
r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)

[[ 8 13]]


In [7]:
r_3 = np.random.random(size=(2, 1))
print(r_3)

[[0.81349505]
 [0.04353953]]


In [8]:
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

[[ 43  63  82  31  87]
 [ 59  42  30  29  32]
 [ 77  33  37  78  96]
 [ 79  20  98 100  54]]


In [9]:
r_5 = np.random.random(size=(4, 5))
print(r_5)

[[0.1585016  0.35705652 0.62010934 0.40563257 0.37072354]
 [0.82674573 0.37739522 0.08464324 0.2303405  0.60683348]
 [0.20911617 0.71247814 0.97319839 0.55382022 0.42005353]
 [0.58807942 0.71943163 0.78606116 0.09850281 0.57701895]]


## Generating Random Choices from an Array

In [25]:
students = np.array([
    "Samia", "Hashim", "Menal", "Hanan",
    "Nejat", "Selim", "Munir", "Nadia",
    "Fahed", "Amer", "Omer", "Ahmed"
])

In [26]:
call_on = np.random.choice(students)
print(call_on)

Samia


In [27]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)

# Is this an effective way to assign breakout groups?
# Not really — np.random.choice samples WITH replacement by default,
# meaning the same student could appear in multiple groups simultaneously.
# To fix this, you'd use replace=False, but that only works for a 1-D output.
# For true group assignment without repeats, you'd shuffle the array and reshape it instead.

[['Amer' 'Omer' 'Menal' 'Fahed']
 ['Nejat' 'Hanan' 'Selim' 'Fahed']
 ['Amer' 'Menal' 'Amer' 'Menal']]


In [23]:
# Probability weights for each of the 12 students:
# Ahmed: 0.00 — zero chance (absent/excused)
# Samia: 0.30 — highest chance, most engaged participant
# Hashim: 0.10
# Selim: 0.10
# Munir: 0.10
# Omer: 0.08
# Fahed: 0.08
# Amer: 0.07
# Nejat: 0.07
# Hanen: 0.05
# Menal: 0.03
# Nadia: 0.02
# Total: 1.00

p_values = [0.00, 0.30, 0.10, 0.10, 0.10, 0.08, 0.08, 0.07, 0.07, 0.05, 0.03, 0.02]

call_on_weighted = np.random.choice(students, size=5, p=p_values)
print(call_on_weighted)

['Fahed' 'Hanan' 'Nadia' 'Menal' 'Nadia']


## Generating a Normal Distribution

In [24]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[10.62426246 17.76895179 15.06446193 14.06578843 11.06280214]
 [17.65445419 17.29404895  5.58981459 13.28888097 14.18823795]
 [22.64213685 19.13425735  8.64600187 15.42632976 11.95448482]
 [10.99083225  9.07152873 11.85013719 12.53823729  3.64549804]]
