# Exercise 1.C Performing operations on arrays

In [7]:
import numpy as np

In [8]:
## Sample Arrays

In [10]:
np.random.seed(42)  # optional — makes results reproducible

r_1 = np.random.randint(1, 10, 5)           # 1-D, 5 integers
r_2 = np.random.randint(1, 10, (2, 5))      # 2-D, 2×5
r_3 = np.random.uniform(-10, 10, (2, 4))    # 2-D floats
r_4 = np.random.randint(1, 10, (2, 5))      # 2-D, 2×5 (same shape as r_2)
r_5 = np.random.randint(1, 10, (3, 3))      # 2-D, 3×3

print(r_1, r_2, r_3, r_4, r_5, sep='\n')

[7 4 8 5 7]
[[3 7 8 5 4]
 [8 8 3 6 5]]
[[ 9.39819704  6.64885282 -5.75321779 -6.36350066]
 [-6.3319098  -3.91515514  0.49512863 -1.36109963]]
[[1 3 7 4 9]
 [3 5 3 7 5]]
[[9 7 2]
 [4 9 2]
 [9 5 2]]


## Permutations

In [11]:
print("Before shuffle:\n", r_4)

Before shuffle:
 [[1 3 7 4 9]
 [3 5 3 7 5]]


In [12]:
np.random.shuffle(r_4)
print("After shuffle:\n", r_4)

After shuffle:
 [[1 3 7 4 9]
 [3 5 3 7 5]]


In [13]:
new_shuffle = np.random.permutation(r_4)
print("new_shuffle:\n", new_shuffle)
print("r_4 (unchanged):\n", r_4)


new_shuffle:
 [[1 3 7 4 9]
 [3 5 3 7 5]]
r_4 (unchanged):
 [[1 3 7 4 9]
 [3 5 3 7 5]]


## Mathematical Operations

In [14]:
print("r_1:", r_1, "  shape:", r_1.shape)
print("r_2:\n", r_2, "  shape:", r_2.shape)
result = np.add(r_1, r_2)
print("r_1 + r_2:\n", result, "  shape:", result.shape)

r_1: [7 4 8 5 7]   shape: (5,)
r_2:
 [[3 7 8 5 4]
 [8 8 3 6 5]]   shape: (2, 5)
r_1 + r_2:
 [[10 11 16 10 11]
 [15 12 11 11 12]]   shape: (2, 5)


In [15]:
print("r_1:", r_1, "  shape:", r_1.shape)
print("r_3:\n", r_3, "  shape:", r_3.shape)
result = np.add(r_1, r_3)
print("r_1 + r_3:\n", result, "  shape:", result.shape)

r_1: [7 4 8 5 7]   shape: (5,)
r_3:
 [[ 9.39819704  6.64885282 -5.75321779 -6.36350066]
 [-6.3319098  -3.91515514  0.49512863 -1.36109963]]   shape: (2, 4)


ValueError: operands could not be broadcast together with shapes (5,) (2,4) 

In [16]:
print("r_2:\n", r_2, "  shape:", r_2.shape)
print("r_4:\n", r_4, "  shape:", r_4.shape)
result = np.add(r_2, r_4)
print("r_2 + r_4:\n", result, "  shape:", result.shape)

r_2:
 [[3 7 8 5 4]
 [8 8 3 6 5]]   shape: (2, 5)
r_4:
 [[1 3 7 4 9]
 [3 5 3 7 5]]   shape: (2, 5)
r_2 + r_4:
 [[ 4 10 15  9 13]
 [11 13  6 13 10]]   shape: (2, 5)


In [18]:
# r_1 shape (5,) vs r_4 shape (2,5) — raises ValueError
# np.add(r_1, r_4)  <-- this would crash because shapes don't match

# r_2 shape (2,5) vs r_4 shape (2,5) — this WORKS, same shape
print(np.add(r_2, r_4))

# adding np.array([1]) to r_4 — broadcasts, adds 1 to everything
print(np.add(np.array([1]), r_4))

# adding np.array([[1]]) to r_4 — same result, still broadcasts
print(np.add(np.array([[1]]), r_4))

# adding np.array([1,1,1,1,1]) to r_4 — adds to each row
print(np.add(np.array([1,1,1,1,1]), r_4))

# adding np.array([[1],[1]]) to r_4 — shape (2,1) broadcasts to (2,5)
print(np.add(np.array([[1],[1]]), r_4))

[[ 4 10 15  9 13]
 [11 13  6 13 10]]
[[ 2  4  8  5 10]
 [ 4  6  4  8  6]]
[[ 2  4  8  5 10]
 [ 4  6  4  8  6]]
[[ 2  4  8  5 10]
 [ 4  6  4  8  6]]
[[ 2  4  8  5 10]
 [ 4  6  4  8  6]]


In [19]:
print(np.add(np.array([1]), r_4))       # adds 1 to every element
print(np.add(np.array([[1]]), r_4))     # same — [[1]] broadcasts across all rows/cols
print(np.add(np.array([1,1,1,1,1]), r_4))  # adds element-wise across each row
# np.add(np.array([[1],[1]]), r_4)  ← same shape (2,1)→(2,5) works fine


[[ 2  4  8  5 10]
 [ 4  6  4  8  6]]
[[ 2  4  8  5 10]
 [ 4  6  4  8  6]]
[[ 2  4  8  5 10]
 [ 4  6  4  8  6]]


## Rounding

In [21]:
print("r_3:\n", r_3)

print("trunc:\n",  np.trunc(r_3))   # drops decimal, toward 0
print("fix:\n",    np.fix(r_3))     # same as trunc
print("floor:\n",  np.floor(r_3))   # rounds down (toward -∞)
print("ceil:\n",   np.ceil(r_3))    # rounds up (toward +∞)
print("round 2dp:\n", np.round(r_3, 2))  # banker's rounding to 2 places

r_3:
 [[ 9.39819704  6.64885282 -5.75321779 -6.36350066]
 [-6.3319098  -3.91515514  0.49512863 -1.36109963]]
trunc:
 [[ 9.  6. -5. -6.]
 [-6. -3.  0. -1.]]
fix:
 [[ 9.  6. -5. -6.]
 [-6. -3.  0. -1.]]
floor:
 [[ 9.  6. -6. -7.]
 [-7. -4.  0. -2.]]
ceil:
 [[10.  7. -5. -6.]
 [-6. -3.  1. -1.]]
round 2dp:
 [[ 9.4   6.65 -5.75 -6.36]
 [-6.33 -3.92  0.5  -1.36]]


## Cumulative Operations

In [22]:
print("r_4:\n", r_4)

print("Total sum:", np.sum(r_4))
print("Sum along axis 0 (per column):\n", np.sum(r_4, axis=0))
print("Sum along axis 1 (per row):\n",    np.sum(r_4, axis=1))
print("Cumulative sum (flat):\n",         np.cumsum(r_4))
print("Cumulative sum along axis 0:\n",   np.cumsum(r_4, axis=0))


r_4:
 [[1 3 7 4 9]
 [3 5 3 7 5]]
Total sum: 47
Sum along axis 0 (per column):
 [ 4  8 10 11 14]
Sum along axis 1 (per row):
 [24 23]
Cumulative sum (flat):
 [ 1  4 11 15 24 27 32 35 42 47]
Cumulative sum along axis 0:
 [[ 1  3  7  4  9]
 [ 4  8 10 11 14]]


## Grocery Problem

In [23]:
# Categories: vegetables, fruits, snacks, beverages
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])
print("bag1:", bag1)
print("bag2:", bag2)
totals = np.sum([bag1, bag2], axis=1)
print(f"The first bag contains {totals[0]} items, "
      f"and the second bag contains {totals[1]} items.")
by_cat = np.add(bag1, bag2)
print(f"There are {by_cat[0]} vegetables, {by_cat[1]} fruits, "
      f"{by_cat[2]} boxes of snacks, and {by_cat[3]} beverages "
      f"in the two grocery bags.")


bag1: [2 3 4 0]
bag2: [4 0 1 2]
The first bag contains 9 items, and the second bag contains 7 items.
There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [30]:
ali   = np.array([5, 4, 6, 4, 2])
ben   = np.array([0, 5, 5, 3, 4])  # missed Monday → 0
carla = np.array([3, 6, 0, 3, 4])  # missed Wednesday → 0
#Combined array and weekly totals
all_knocks = np.array([ali, ben, carla])
print("all_knocks:\n", all_knocks)

# Per-person total (sum each row)
per_person = np.sum(all_knocks, axis=1)
print(f"Ali: {per_person[0]}, Ben: {per_person[1]}, Carla: {per_person[2]}")
print("Group total:", np.sum(all_knocks)) 

#Rolling estimated votes (every 2 knocks → 1 vote)
# Daily totals for the whole group
daily_knocks = np.sum(all_knocks, axis=0)
print("Daily knocks:", daily_knocks)

# Cumulative total by day, then halve it
rolling_votes = np.cumsum(daily_knocks) * 0.5
print("Rolling estimated votes by day:", rolling_votes) 

all_knocks:
 [[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]
Ali: 21, Ben: 17, Carla: 16
Group total: 54
Daily knocks: [ 8 15 11 10 10]
Rolling estimated votes by day: [ 4.  11.5 17.  22.  27. ]
